### ISSUE TITLE
Problem with facebookModule and Android

### ISSUE THREAD

**Issue by boardmain** [arleyandrada/PushClient#107]
if i use the module and im using the moduel facebook
i have this errors in the build time

```

[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.impl.LogFactoryImpl$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.impl.LogFactoryImpl$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.impl.LogFactoryImpl$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.impl.SimpleLog$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.impl.WeakHashtable$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$4) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$5) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.shaded.apache.commons.logging.LogFactory$6) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL ERROR:
[ERROR] java.lang.OutOfMemoryError: Java heap space
[ERROR]         at com.android.dx.ssa.Dominators$DfsWalker.visitBlock(Dominators.java:259)
[ERROR]         at com.android.dx.ssa.SsaMethod.forEachBlockDepthFirst(SsaMethod.java:783)
[ERROR]         at com.android.dx.ssa.Dominators.run(Dominators.java:185)
[ERROR]         at com.android.dx.ssa.Dominators.make(Dominators.java:90)
[ERROR]         at com.android.dx.ssa.DomFront.run(DomFront.java:86)
[ERROR]         at com.android.dx.ssa.SsaConverter.placePhiFunctions(SsaConverter.java:297)
[ERROR]         at com.android.dx.ssa.SsaConverter.convertToSsaMethod(SsaConverter.java:51)
[ERROR]         at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:98)
[ERROR]         at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:72)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:299)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:139)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:94)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:682)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
[ERROR]         at com.android.dx.command.dexer.Main.access$600(Main.java:78)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:596)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:230)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:199)
[ERROR]         at com.android.dx.command.Main.main(Main.java:103)

```

**Comment by arleyandrada** [comment]
I've never seen this error message before.
I will to update my workspace and repeat all the tests.

I'm sorry for the late reply. I've been missing in recent months because of health problems and unable to work on my projects. I am currently checking and solving all pending issues. Please check back me if I can help in something else. Thank you!

**Comment by arleyandrada** [comment]
Hi Samuele,

I sent a email to you containing a new version of PushClient module.
Please, check if your issues was resolved.

Regards,

Arley

**Comment by Jitendran** [comment]
Are you using more libraries with project ?
This issue generate due to cross the limit of delvic machine 65K methods.
If we use more jar file and library project with application then it cross the method limit. We need to break the project in 2 parts or delete the isLibrary or jar file from project.

**Comment by arleyandrada** [comment]
Yes, my PushClient module use the required Google Play Services library. It is a big library.

The latest version of my PushClient module is compatible with the latest versions of Titanium modules: Facebook, Ti.map, Ti.Cloudpush.

**Comment by arleyandrada** [comment]
Related to the problem:
So far there is no others users with this problem and I suggest that, for a while, you to downgrade the XCode version or everything else to keep your app and my module working fine together.

Unfortunately I am without my work environment (without my macbook) and therefore I am unable to work in the tests would be needed.

Please, let me know if the downgrade was successful or if you found any other solution.

Sorry.
