### ISSUE TITLE
Android: The Google Play services resources were not found Ti SDK 6.0.0.GA

### ISSUE THREAD

**Issue by csemrm** [arleyandrada/PushClient#157]
[ERROR] :  Zygote: v2
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[ERROR] :  TiApplication: (AsyncTask #1) [823,823] Sending event: exception on thread: AsyncTask #1 msg:java.lang.RuntimeException: An error occurred while executing doInBackground(); Titanium 6.0.0,2016/11/13 01:23,undefined
[ERROR] :  TiApplication: java.lang.RuntimeException: An error occurred while executing doInBackground()
[ERROR] :  TiApplication: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
[ERROR] :  TiApplication: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
[ERROR] :  TiApplication: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
[ERROR] :  TiApplication: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
[ERROR] :  TiApplication: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[ERROR] :  TiApplication: 	at java.lang.Thread.run(Thread.java:818)
[ERROR] :  TiApplication: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/zzc;
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zzde(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
[ERROR] :  TiApplication: 	at br.com.arlsoft.pushclient.PushClientModule$1.doInBackground(PushClientModule.java:239)
[ERROR] :  TiApplication: 	at br.com.arlsoft.pushclient.PushClientModule$1.doInBackground(PushClientModule.java:231)
[ERROR] :  TiApplication: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
[ERROR] :  TiApplication: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[ERROR] :  TiApplication: 	... 4 more
[ERROR] :  TiApplication: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.zzc" on path: DexPathList[[zip file "/data/app/com.medsymphony.housecalls-1/base.apk"],nativeLibraryDirectories=[/data/app/com.medsymphony.housecalls-1/lib/arm, /data/app/com.medsymphony.housecalls-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
[ERROR] :  TiApplication: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[ERROR] :  TiApplication: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[ERROR] :  TiApplication: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[ERROR] :  TiApplication: 	... 10 more
[ERROR] :  TiApplication: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.zzc
[ERROR] :  TiApplication: 		at java.lang.Class.classForName(Native Method)
[ERROR] :  TiApplication: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[ERROR] :  TiApplication: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[ERROR] :  TiApplication: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[ERROR] :  TiApplication: 		... 11 more
[ERROR] :  TiApplication: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
[ERROR] :  AndroidRuntime: Process: com.medsymphony.housecalls, PID: 20706
[ERROR] :  AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
[ERROR] :  AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
[ERROR] :  AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[ERROR] :  AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
[ERROR] :  AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/zzc;
[ERROR] :  AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zzde(Unknown Source)
[ERROR] :  AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
[ERROR] :  AndroidRuntime: 	at br.com.arlsoft.pushclient.PushClientModule$1.doInBackground(PushClientModule.java:239)
[ERROR] :  AndroidRuntime: 	at br.com.arlsoft.pushclient.PushClientModule$1.doInBackground(PushClientModule.java:231)
[ERROR] :  AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[ERROR] :  AndroidRuntime: 	... 4 more
[ERROR] :  AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.zzc" on path: DexPathList[[zip file "/data/app/com.medsymphony.housecalls-1/base.apk"],nativeLibraryDirectories=[/data/app/com.medsymphony.housecalls-1/lib/arm, /data/app/com.medsymphony.housecalls-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
[ERROR] :  AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[ERROR] :  AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[ERROR] :  AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[ERROR] :  AndroidRuntime: 	... 10 more
[ERROR] :  AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.zzc
[ERROR] :  AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
[ERROR] :  AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[ERROR] :  AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[ERROR] :  AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[ERROR] :  AndroidRuntime: 		... 11 more
[ERROR] :  AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by DouglasHennrich** [comment]
Any news about this error? @arleyandrada

**Comment by ErikDohmen-xx** [comment]
Having the same error here, any news @arleyandrada

**Comment by ErikDohmen-xx** [comment]
@arleyandrada  I tried to run the sample app, but that didn't work either (btw I tried it on my phone with google services).

**Comment by yazzneortre** [comment]
This is because the version ("9683000") of com.google.android.gms have deprecated methods. For now, I compiled with "7571000" number version and works fine.

**Comment by shacharudi** [comment]
Hi @arleyandrada ,
First of all, thank you for making this module, I was looking for something to solve Push Notifications on Appcelerator 6.0 and your module looks very promising!

While trying to use it on Android I ran into the problem described in this issue and I was wondering if you could explain to me how to solve it.
this is what I'm getting:

`GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.`

I'm was testing this on two different Android devices both have Google Play Services installed.
Do I need to include anything else except the module and the Provider? 

I'm using this version of the module: 
https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-android-1.20.zip

Thank you!

**Comment by arleyandrada** [comment]
I am unable to perform tests, however I am releasing the new version based on what was sent by @csemrm

My free developer account was rejected by the Appcelerator team and I don't want to pay for a new account.

https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-android-1.21.zip

**Comment by arleyandrada** [comment]
Waiting for tests from @shacharudi or @yazzneortre or @ErikDohmen or @DouglasHennrich
Thanks!

**Comment by kerberosargos** [comment]
Hi, firstly thank  @arleyandrada  your for your developing. I have updated my Appcelerator environment to SDK 6.0.1GA After that your old release didn't work. For this reason I update your module to 1.2.1 but I am getting error as below when I compile my project;

`Message: Uncaught The meta-data tag in your app's AndroidManifest.xml does not have the right value. Expected 7571000 but found 9683000. You must have the following declaration within the <application> element: <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`

How can I solve this issue?

Thank you in advance.
@shacharudi @yazzneortre @ErikDohmen @DouglasHennrich

**Comment by ErikDohmen-xx** [comment]
@kerbooo just to be sure:

- you've got the correct version connected 1.2.1 (latest)
- you've got the correct sdk 6.0.1GA
- you did a project => clean action in order to remove all older references
cause it looks like there's an old reference somewhere towards the old version of the pushclient

**Comment by kerberosargos** [comment]
@ErikDohmen Thank you very much for your reply. I have did everything as you wrote. I removed all modules in my project and I update my SDK version. Anyway it gives me error as I wrote.

**Comment by ErikDohmen-xx** [comment]
@kerbooo did you clean your project build cache as well with the option from the top bar in Appcelerator Studio => Project => clean

**Comment by kerberosargos** [comment]
@ErikDohmen I am not sure I think googleplay-service-base.jar file version which in lib folder not correct.

**Comment by kerberosargos** [comment]
@ErikDohmen yes I am cleaning my project before every build.

**Comment by ErikDohmen-xx** [comment]
@kerbooo the complete list of files you need should be in the latest distribution of 1.21 just drop the 1.21 directory within the br.com.arlsoft.pushclient directory and you should be fine

**Comment by kerberosargos** [comment]
When I drop all file and remove codes from my project it is working and I
have only this module in my project.

19 Şub 2017 16:47 tarihinde "Erik Dohmen" <notifications@github.com> yazdı:

**Comment by ErikDohmen-xx** [comment]
Good to hear, that's a start now add more and more of your code you need and I hope it will keep working for you. If not, just drop a line here and we will see what to do next

**Comment by kerberosargos** [comment]
OK I need to know  all google play base jar file version is different or
not? I need to use 3 modules with my ptoject. Google analytics, admob and
push message. My older sdk was 5.1 and I could use all of them together.
After update I don't use them.

19 Şub 2017 16:56 tarihinde "Erik Dohmen" <notifications@github.com> yazdı:

**Comment by fahad86** [comment]
@kerbooo , were you able to get this working with other modules that use google-play-services?

I am getting conflict errors. And if I change all modules to use the same lib, then I get:

` The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.`

**Comment by shacharudi** [comment]
I was able to solve my issue by going back to on older appcelerator sdk version and use an older solutions, it wasn't optimal but I had to release the app. on my next project ill use this module again and test it.

Thanks again for sharing this module, I'm looking forward to be using it.

**Comment by kerberosargos** [comment]
Hi Guys I solved Google Play Services conflict for using more Titanium modules. I have recorded a screencast for solution. You can find it from https://youtu.be/Coei6zvPIys

May be that is help for somebody...

**Comment by danny005** [comment]
google-play-services-iid.jar was missing in the lib dir.

You can get it e.g. from this module:

https://github.com/appcelerator/titanium_mobile/blob/master/support/module/packaged/ti.cloudpush-android-4.0.3.zip

If you want to use version 1.21 along the current latest Ti.Map version (3.1.1), you have to edit timodule.xml with the correct gms version: 9683000
