### ISSUE TITLE
Module PushClient Error

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#39]
Hi,
I've purchased the module "PushClient" some time ago but I have problems in using.

When I include it and compile gives me the following error:

```
[INFO] :   Running dexer: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java "-Xmx1024M" "-XX:-UseGCOverheadLimit" "-Djava.ext.dirs=/Users/xxxxx/Library/android-sdk-macosx/platform-tools" "-jar" "/Users/xxxxx/Library/android-sdk-macosx/build-tools/21.1.1/lib/dx.jar" "--dex" "--output=/Users/xxxxx/Documents/Titanium_Studio_Workspace/I Portali/build/android/bin/classes.dex" "/Users/xxxxx/Documents/Titanium_Studio_Workspace/I Portali/build/android/bin/classes" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/lib/titanium-verify.jar" "/Users/xxxxx/Library/Application Support/Titanium/modules/android/ti.map/2.2.2/map.jar" "/Users/xxxxx/Library/Application Support/Titanium/modules/android/ti.map/2.2.2/lib/google-play-services.jar" "/Users/xxxxx/Documents/Titanium_Studio_Workspace/I Portali/modules/android/br.com.arlsoft.pushclient/1.6/pushclient.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/kroll-v8.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-analytics.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/aps-analytics.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-android.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/jaxen-1.1.1.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/ti-commons-codec-1.3.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/kroll-common.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/titanium.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-app.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-ui.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/nineoldandroids-appc-2.4.0.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-filesystem.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-media.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-appcompat.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/android-support-v4.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/android-support-v7-appcompat.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-locale.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-network.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/thirdparty.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-xml.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-utils.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-geolocation.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-accelerometer.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-contacts.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-map.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-calendar.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-gesture.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-platform.jar" "/Users/xxxxx/Library/Application Support/Titanium/mobilesdk/osx/3.4.1.GA/android/modules/titanium-database.jar"

[ERROR] :  Failed to run dexer:

[ERROR] :  

[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:

[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/R$color;

[ERROR] :  at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)

[ERROR] :  at com.android.dx.dex.file.DexFile.add(DexFile.java:161)

[ERROR] :  at com.android.dx.command.dexer.Main.processClass(Main.java:732)

[ERROR] :  at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)

[ERROR] :  at com.android.dx.command.dexer.Main.access$300(Main.java:82)

[ERROR] Application Installer abnormal process termination. Process exit value was 1

[ERROR] :  at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)

[ERROR] :  at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)

[ERROR] :  at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)

[ERROR] :  at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)

[ERROR] :  at com.android.dx.command.dexer.Main.processOne(Main.java:632)

[ERROR] :  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)

[ERROR] :  at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)

[ERROR] :  at com.android.dx.command.dexer.Main.run(Main.java:245)

[ERROR] :  at com.android.dx.command.dexer.Main.main(Main.java:214)

[ERROR] :  at com.android.dx.command.Main.main(Main.java:106)

[ERROR] :  1 error; aborting
```

I Use Appcelerator Version: 3.4.1, Project "Mobile Primary"

Other modules configured: ti.map

Only Android Project.

Thanks in advance,

**Comment by arleyandrada** [comment]
Attached is a new fixed module version.
It's still waiting for an approval from Appcelerator Marketplace.

Regards,

Arley

[ attachment removed ]
