### ISSUE TITLE
Crash on Android PushClient When in Background

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#80]
Hi!

I bought your library a bit ago and I'm almost done integrating it.

Your library works great on Android when the app is in the foreround.

However, I am getting a crash on Android when a push comes in while the app is in the background.

Here's the crash log from the moment the GCM message comes in...

```
04-13 15:38:21.389: I/GCM(3371): GCM message com.halpin.distantcomfort 0:1428961101364277%7f26a0caf9fd7ecd
04-13 15:38:21.427: I/ActivityManager(923): Start proc com.halpin.distantcomfort for broadcast com.halpin.distantcomfort/br.com.arlsoft.pushclient.GCMBroadcastReceiver: pid=10282 uid=10249 gids={50249, 3003, 1028, 1015}
04-13 15:38:21.459: I/TiApplication(10282): (main) [0,0] checkpoint, app created.
04-13 15:38:21.640: I/TiApplication(10282): (main) [181,181] Titanium 3.5.0 (2015/01/12 15:33 0014f83)
04-13 15:38:21.767: D/dalvikvm(10282): Trying to load lib /data/app-lib/com.halpin.distantcomfort-2/libtiverify.so 0x41f1e0e8
04-13 15:38:21.768: W/linker(10282): libtiverify.so has text relocations. This is wasting memory and is a security risk. Please fix.
04-13 15:38:21.769: D/dalvikvm(10282): Added shared lib /data/app-lib/com.halpin.distantcomfort-2/libtiverify.so 0x41f1e0e8
04-13 15:38:21.771: D/dalvikvm(10282): Trying to load lib /data/app-lib/com.halpin.distantcomfort-2/libstlport_shared.so 0x41f1e0e8
04-13 15:38:21.772: W/linker(10282): libstlport_shared.so has text relocations. This is wasting memory and is a security risk. Please fix.
04-13 15:38:21.774: D/dalvikvm(10282): Added shared lib /data/app-lib/com.halpin.distantcomfort-2/libstlport_shared.so 0x41f1e0e8
04-13 15:38:21.775: D/dalvikvm(10282): No JNI_OnLoad found in /data/app-lib/com.halpin.distantcomfort-2/libstlport_shared.so 0x41f1e0e8, skipping init
04-13 15:38:21.776: D/dalvikvm(10282): Trying to load lib /data/app-lib/com.halpin.distantcomfort-2/libkroll-v8.so 0x41f1e0e8
04-13 15:38:21.778: W/linker(10282): libkroll-v8.so has text relocations. This is wasting memory and is a security risk. Please fix.
04-13 15:38:21.787: D/dalvikvm(10282): Added shared lib /data/app-lib/com.halpin.distantcomfort-2/libkroll-v8.so 0x41f1e0e8
04-13 15:38:21.787: I/TiApplication(10282): (main) [147,328] Titanium Javascript runtime: v8
04-13 15:38:21.813: W/dalvikvm(10282): threadid=12: thread exiting with uncaught exception (group=0x41652d40)
04-13 15:38:21.815: E/AndroidRuntime(10282): FATAL EXCEPTION: IntentService[GCMIntentService]
04-13 15:38:21.815: E/AndroidRuntime(10282): Process: com.halpin.distantcomfort, PID: 10282
04-13 15:38:21.815: E/AndroidRuntime(10282): java.lang.NullPointerException
04-13 15:38:21.815: E/AndroidRuntime(10282):     at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at org.json.JSONTokener.nextValue(JSONTokener.java:94)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at org.json.JSONObject.<init>(JSONObject.java:155)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at org.json.JSONObject.<init>(JSONObject.java:172)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at br.com.arlsoft.pushclient.PushClientModule.sendNotification(PushClientModule.java:458)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at br.com.arlsoft.pushclient.GCMIntentService.onHandleIntent(GCMIntentService.java:87)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at android.os.Looper.loop(Looper.java:136)
04-13 15:38:21.815: E/AndroidRuntime(10282):     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here's the push I send (exactly same when in foreground)...

```
{ 
   "GCM":{ 
      "data":{ 
         "message":"Check out these awesome deals!",
         "url":"www.amazon.com"
      },
      "time_to_live":3600,
      "collapse_key":"deals"
   }
}
```

Here's the code (nearly identical to your sample)...

```
var eventCallback = function(event)
    {
        Ti.API.error("eventCallback:" + JSON.stringify(event));

        if (!event)
        {
            Ti.API.error("Callback:\n\nInvalid callback");
            alert('Callback:\n\nInvalid callback');
            // Should never happen...
        }
        else if (event.mode == PushClient.MODE_FOREGROUND)
        {
            Ti.API.error("Callback in Foreground:\n\n" + JSON.stringify(event.data));
            alert('Callback in Foreground:\n\n' + JSON.stringify(event.data));
            // Push data received with app in foreground
        }
        else if (event.mode == PushClient.MODE_CLICK)
        {
            Ti.API.error("Callback from Click:\n\n" + JSON.stringify(event.data));
            alert('Callback from Click:\n\n' + JSON.stringify(event.data));
            // Push data received when user clicks in notification message
        }
        else if (event.mode == PushClient.MODE_BACKGROUND)
        {
            alert('Callback from Silent:\n\n' + JSON.stringify(event.data));
            // Requires set remote-notification UIBackgroundModes in tiapp.xml
            PushClient.endBackgroundHandler(event.data.handlerId);
            // Put the application back to sleep before any UI interations
            Ti.API.error("Callback from Silent:\n\n" + JSON.stringify(event.data));
            // Push data received with app in background
        }
        else if (event.mode == PushClient.MODE_ACTION)
        {
            alert('Callback from Action:\n\n'+event.category+'\n'+event.identifier+'\n\n' + JSON.stringify(event.data));
            Ti.API.error("Callback from Action:\n\n"+event.category+"\n"+event.identifier+"\n\n" + JSON.stringify(event.data));
            // Push data received when user choose an action from notification message
        }
        else
        {
            alert('Callback:\n\n' + JSON.stringify(event.data));
            Ti.API.error("Callback:\n\n" + JSON.stringify(event.data));
            // Should never happen...
        }
    };
```

I never see an alert or a log message when in the background.  It immediately fails with the crasher.

Any help would be greatly appreciated.  I will have to abandon your library if I can't get this resolved.

thanks,

**Comment by arleyandrada** [comment]
Try to change your payload data from "message" to "alert" or "text".

Sorry by the delay in response.

Regards,

Arley

```
// Notification properties:
// "alert" (String) to text message - or "text" to Android
// "sound" (String) to sound file to play - "default" to Android default sound
// "badge" (Int) to iOS badge count indicator
// "content-available" (Int) to iOS background notification
// -->> Requires set remote-notification UIBackgroundModes in tiapp.xml
// "notificationId" (Int) to Android notification identification
// "title" (String) to override Android notification title - default app name
// "ticker" (String) to override Android ticker message - default alert message
// "vibrate" (Boolean) to use default Android device vibration
// "lights" (Boolean) to use default Android device lights
// "smallIcon" (String) set small icon to Android notification from assets
// "largeIcon" (String) set large icon to Android notification from local file or url
// "category" (String) to iOS 8 interactive notification
```

**Comment by somefakeuser** [comment]
Arley,

Thanks for the response!

Still doesn't work.

These pushes all gave me the same error reported below...

```
{
   "GCM":{
      "data":{
         "text":"Check out these awesome deals!"
      }
   }
}

{
   "GCM":{
       "text": "my text"
         }
}

{
   "GCM":{
"data": {
       "alert": "my text"
            }
         }
}

{
   "GCM":{
       "alert": "my text"
         }
}
```

Ideas?  Can you send me one that works?

thanks,

**Comment by DanielBcnicode** [comment]
Hi,
do you have solved this problem? I'm in the same situation.
Thanks

**Comment by arleyandrada** [comment]
Hi Daniel,

Yes, it was solved by the user.
He replied as follows:

```
"Nevermind.  I got it working.  I had to have both "message" and "alert" for it to work."
```

Regards,

Arley
